language: python

python:
  - "3.6"

install:
  - pip install -r requirements.test.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source typycal -m py.test
  - coverage report -m

after_success:
  - coveralls